### ISSUE TITLE
installation is still missing something...

### ISSUE THREAD

**Issue by thex-at** [thex-at/pimatic-holidays#2]
git cloning the plugin works fine but i still have to run "npm install" to get the dependencies and it's still bugging me for some peer dependencies...

have to find out how an installation should work for a plugin...

**Comment by thost96** [comment]
This is a normal behavior if you clone a plugin from github. If you publish the plugin to npmjs.com, npm will automatically install all needed dependencies ;-) 

The peer dependencies should be some pimatic packages, which can be ignored, due to the fact, that you manually install the plugin.
